language: node_js
node_js: v8
sudo: false
addons:
  ssh_known_hosts: ssh-oncletom.alwaysdata.net

env:
  - HUGO_VERSION="0.31" PATH="$HOME/.local/bin:$PATH"

before_install:
  - curl -sSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar xzv
  - chmod +x hugo && mkdir -p $HOME/.local/bin && mv hugo $HOME/.local/bin

before_script:
  - openssl aes-256-cbc -K $encrypted_7eacc5fbf488_key -iv $encrypted_7eacc5fbf488_iv -in id_ed25519.enc -out /tmp/id_ed25519 -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_ed25519
  - ssh-add /tmp/id_ed25519

after_success:
  - npm run generate-cache
  - npm run generate-thumbs
  - npm run build

deploy:
- provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
